// Editable IPTC metadata + metadata presets (gap-analysis P1-7).
//
// LrC's mechanism: a semi-pro stamps title/caption/copyright/creator on
// deliverables via a metadata preset -- "every new shoot gets my copyright
// line" -- rather than typing six fields per photo. This module is the data
// layer for that: six IPTC fields stored whole under ONE `iptc` key on the
// FileRecord row (schemaless, no version bump, same stance as the culling
// marks), and presets as rows in their own store.
//
// PARENT ACTION REQUIRED: src/catalog/db.ts must create the preset store in
// upgradeDB -- under the NEXT version guard (`if (event.oldVersion < 6) {
// db.createObjectStore('metadataPresets', { keyPath: 'id' }); }`), and bump
// DB_VERSION from 5 to 6. Until that lands, listMetadataPresets() below
// returns [] (a missing store is tolerated) and save/delete reject with a
// message naming the store, so the app boots and reads work either way.
// Keywords deliberately did NOT need a store (the list is derived from file
// rows -- see keywords.ts); presets do because they exist before any photo
// has them.
//
// The six fields mirror LrC's IPTC Status/Content subset that a semi-pro
// actually fills; the full IPTC Extension set is Nice-to-have per the
// gap analysis and stays out.

import type { FileRecord } from './types';

export interface IptcFields {
  title?: string;
  caption?: string;
  headline?: string;
  creator?: string;
  copyright?: string;
  credit?: string;
}

// The FileRecord rows gained an `iptc` bag without touching types.ts (which
// this module does not own -- adding the field there is a one-line parent
// convenience, not a requirement; IDB rows are schemaless).
export type IptcFileRow = FileRecord & { iptc?: IptcFields };

export interface MetadataPreset {
  id: string; // generated by the UI (newPresetId) so saves and edits are idempotent puts
  name: string;
  fields: IptcFields;
}

export const METADATA_PRESET_STORE = 'metadataPresets';

// Canonical field order: display order in describePreset and diffIptc, and the
// key list every mapper below walks. Copyright leads because it is the field
// the preset exists for.
const IPTC_KEYS = ['copyright', 'creator', 'credit', 'caption', 'title', 'headline'] as const;

export type IptcFieldKey = (typeof IPTC_KEYS)[number];

// ---- pure -------------------------------------------------------------------

function clean(value: string | undefined): string {
  return (value ?? '').trim();
}

// A patch from a preset: keys the preset leaves blank are ABSENT, not empty
// strings. That is what makes applying `{ copyright: '...' }` to a photo that
// already has a caption leave the caption alone -- the blank-out bug class: if
// the patch carried `caption: ''`, `{ ...file.iptc, ...patch }` would wipe it.
export function presetToPatch(preset: MetadataPreset): Partial<IptcFields> {
  const patch: Partial<IptcFields> = {};
  for (const key of IPTC_KEYS) {
    const value = clean(preset.fields[key]);
    if (value) patch[key] = value;
  }
  return patch;
}

// Panel form -> storable fields: trim, and drop blanks so an untouched box
// doesn't persist a sea of empty strings. Input keys are the field names
// (what the iptc-* inputs map to); unknown keys are ignored.
export function fieldsFromPresetForm(form: Record<string, string>): IptcFields {
  const fields: IptcFields = {};
  for (const key of IPTC_KEYS) {
    const value = clean(form[key]);
    if (value) fields[key] = value;
  }
  return fields;
}

// One-line summary for a preset row / its tooltip: 'Copyright · Creator ·
// Caption'. Lets someone pick the right preset from a dropdown of six without
// applying each to see what it does.
export function describePreset(preset: MetadataPreset): string {
  const filled = IPTC_KEYS.filter((key) => clean(preset.fields[key]));
  if (filled.length === 0) return 'No fields set';
  return filled.map((key) => key[0].toUpperCase() + key.slice(1)).join(' · ');
}

// Which fields differ between two field sets (treating absent and '' as the
// same empty value). The UI uses it to grey the Apply button when the
// selection already matches, and tests use it to prove a patch applied
// nothing outside its scope.
export function diffIptc(a: IptcFields, b: IptcFields): IptcFieldKey[] {
  return IPTC_KEYS.filter((key) => clean(a[key]) !== clean(b[key]));
}

// id for a brand-new preset. crypto.randomUUID is available in every Chromium
// context we run in; the fallback only exists so a non-secure context (file://
// smoke test) can't throw.
export function newPresetId(): string {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }
  return `preset-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

function isValidPresetRow(row: unknown): row is MetadataPreset {
  if (typeof row !== 'object' || row === null) return false;
  const r = row as MetadataPreset;
  return typeof r.id === 'string' && r.id.length > 0 && typeof r.name === 'string' && r.name.length > 0 && typeof r.fields === 'object' && r.fields !== null;
}

// ---- IndexedDB: per-file IPTC ------------------------------------------------
// Same discipline as setCull / setFileKeywords: read the WHOLE row, change only
// the `iptc` key, write the whole row back. A blind partial put would drop the
// file `handle`; a write that skipped the read would clobber a rating a
// keystroke earlier. Everything lives under the single `iptc` key (not six
// loose fields) so a partial update can never tear a half-written record and
// backup/restore has one object to carry.

export function setFileIptc(
  db: IDBDatabase,
  fileIds: readonly number[],
  fields: IptcFields,
): Promise<void> {
  return new Promise((resolve, reject) => {
    if (fileIds.length === 0) {
      resolve();
      return;
    }
    let tx: IDBTransaction;
    try {
      tx = db.transaction('files', 'readwrite');
    } catch (err) {
      reject(err);
      return;
    }
    const store = tx.objectStore('files');
    let settled = false;
    const fail = (error: unknown) => {
      if (settled) return;
      settled = true;
      reject(error instanceof Error ? error : new Error('IPTC write failed'));
    };

    for (const fileId of fileIds) {
      const getRequest = store.get(fileId);
      getRequest.onsuccess = () => {
        const record = getRequest.result as IptcFileRow | undefined;
        if (!record) {
          // Same contract as setCull: a vanished row is an error, not a skip.
          fail(new Error(`File ${fileId} not in catalog`));
          try {
            tx.abort();
          } catch {
            /* already aborted */
          }
          return;
        }
        const merged = mergeIptc(record.iptc, fields);
        record.iptc = merged;
        if (Object.keys(merged).length === 0) delete record.iptc;
        store.put(record);
      };
      getRequest.onerror = () => fail(getRequest.error);
    }

    tx.oncomplete = () => {
      if (settled) return;
      settled = true;
      resolve();
    };
    tx.onabort = () => fail(tx.error ?? new Error('IPTC write aborted'));
    tx.onerror = () => fail(tx.error ?? new Error('IPTC write failed'));
  });
}

// Merge semantics for the `iptc` bag: a key PRESENT in the patch replaces (an
// empty string clears that field -- that's the Metadata-panel blur path), a
// key ABSENT from the patch keeps what the row had (that's presetToPatch's
// guarantee). Callers that must never blank anything apply a presetToPatch
// result, never a raw form.
export function mergeIptc(existing: IptcFields | undefined, patch: IptcFields): IptcFields {
  const merged: IptcFields = {};
  for (const key of IPTC_KEYS) {
    const value = key in patch ? clean(patch[key]) : clean(existing?.[key]);
    if (value) merged[key] = value;
  }
  return merged;
}

// ---- IndexedDB: metadata presets ----------------------------------------------
// Tolerant reads, loud writes: the app shipped before this store existed and a
// user mid-catalog must still open the app and keep tagging (see the PARENT
// ACTION REQUIRED header).

function hasPresetStore(db: IDBDatabase): boolean {
  try {
    return db.objectStoreNames.contains(METADATA_PRESET_STORE);
  } catch {
    // A closed connection throws on objectStoreNames access; treat it the same
    // as "no store" so reads stay non-fatal and writes carry a clearer message.
    return false;
  }
}

function missingStoreError(op: string): Error {
  return new Error(
    `Cannot ${op}: the '${METADATA_PRESET_STORE}' store does not exist yet — db.ts needs the v6 upgrade (see src/catalog/iptc.ts)`,
  );
}

export function listMetadataPresets(db: IDBDatabase): Promise<MetadataPreset[]> {
  if (!hasPresetStore(db)) return Promise.resolve([]);
  return new Promise((resolve) => {
    let tx: IDBTransaction;
    try {
      tx = db.transaction(METADATA_PRESET_STORE, 'readonly');
    } catch {
      // Racing a version change, or the store vanished: read as "no presets".
      resolve([]);
      return;
    }
    const request = tx.objectStore(METADATA_PRESET_STORE).getAll();
    request.onsuccess = () => {
      // Corrupt/stale rows are dropped, not fatal (presetsStore.ts stance).
      const rows = (request.result as unknown[]).filter(isValidPresetRow);
      rows.sort((a, b) => a.name.localeCompare(b.name)); // the picker lists by name
      resolve(rows);
    };
    request.onerror = () => resolve([]); // a read NEVER breaks the app (see header)
  });
}

export function saveMetadataPreset(db: IDBDatabase, preset: MetadataPreset): Promise<void> {
  if (!preset.id) return Promise.reject(new Error('Preset needs an id (newPresetId)'));
  if (!preset.name.trim()) return Promise.reject(new Error('Preset needs a name'));
  if (!hasPresetStore(db)) return Promise.reject(missingStoreError('save metadata presets'));
  return new Promise((resolve, reject) => {
    let tx: IDBTransaction;
    try {
      tx = db.transaction(METADATA_PRESET_STORE, 'readwrite');
    } catch (err) {
      reject(err instanceof Error ? err : missingStoreError('save metadata presets'));
      return;
    }
    const request = tx.objectStore(METADATA_PRESET_STORE).put(preset);
    request.onsuccess = () => resolve();
    request.onerror = () => reject(request.error);
    tx.onabort = () => reject(tx.error ?? new Error('Preset save aborted'));
  });
}

export function deleteMetadataPreset(db: IDBDatabase, id: string): Promise<void> {
  if (!hasPresetStore(db)) return Promise.reject(missingStoreError('delete metadata presets'));
  return new Promise((resolve, reject) => {
    const tx = db.transaction(METADATA_PRESET_STORE, 'readwrite');
    const request = tx.objectStore(METADATA_PRESET_STORE).delete(id);
    request.onsuccess = () => resolve();
    // Real IDB raises NotFoundError for an unknown key; surface it as text the
    // UI can show instead of a raw DOMException.
    request.onerror = () => reject(new Error(`No metadata preset '${id}' in the catalog`));
    tx.onabort = () => reject(tx.error ?? new Error('Preset delete aborted'));
  });
}
